### ISSUE TITLE
Can't build the project

### ISSUE THREAD

**Issue by tikhonbelousko** [asamiller/den#2]
I did everything following your guide but came across this error. 

![screen shot 2015-05-08 at 13 08 04](https://cloud.githubusercontent.com/assets/2707291/7534443/5fdceb14-f583-11e4-83a7-32ea2800fb87.png)

Here is my package.json

``` javascript
{
  "name": "Den",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node_modules/react-native/packager/packager.sh"
  },
  "dependencies": {
    "cheerio": "^0.19.0",
    "lodash": "^3.6.0",
    "moment": "^2.10.2",
    "react-native": "^0.4.0",
    "string": "^3.1.1"
  }
}
```

**Comment by dsibiski** [comment]
Looks like the real error is:

`message: Requiring unknown module "util". If you are sure the module is there, try restarting the packager."`

I tried to scan the app to see where 'util' was being required but couldn't find it...

**Comment by dsibiski** [comment]
@DaZzz It's because we didn't read the instructions...

Need to move the "cheerio" folder in the root into node_modules...move it, restart the package manager and it works just fine.

**Comment by jDeppen** [comment]
I had trouble too. For anyone else reading this, be sure to delete cheerio in node_modules then move cheerio into node_modules from the root. Sublime was merging it rather than overwriting.

**Comment by tikhonbelousko** [comment]
Well... I think I merged cherio with its npm version, that was a problem. Now everything is ok.  

Thanks!

:+1:

**Comment by asamiller** [comment]
Sorry, this is a hacky workaround. Hopefully JSON support will land soon. They've got it internally: facebook/react-native#231

**Comment by deresegetachew** [comment]
There is no cheerio in the root folder what do you mean by move it from the root folder
