### ISSUE TITLE
Object not a fn (evaluating 'fetch')

### ISSUE THREAD

**Issue by winkler1** [asamiller/den#4]
This looks slick..followed instructions about cheerio, got this @runtime -- 

![image](https://cloud.githubusercontent.com/assets/883896/7621646/59bb9e9e-f996-11e4-8095-1bbaf70ef7bc.png)

**Comment by jeffbski** [comment]
+1
 Me too. I did have to add version to cheerio/package.json to get it to run, but once I did search, I got this screen.

**Comment by jeffbski** [comment]
https://github.com/asamiller/den/pull/3

**Comment by asamiller** [comment]
I got this fixed. Give it a shot now.
