### ISSUE TITLE
Error while loading project in Xcode Version 6.4 (6E14)

### ISSUE THREAD

**Issue by ajaybeniwal** [asamiller/den#5]
I have downloaded the project and trying to run the project in Xcode V 6.4 , I am getting below error 
ld: library not found for -lRCTWebSocketDebugger
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by strazi** [comment]
I'm seeing the same error in 6.3.1

**Comment by tradziej** [comment]
Easy evading is to remove `libRTCWebSocketDebugger` from Linked frameworks and Libraries

**Comment by realph** [comment]
Having this same issue. Where do I remove `libRTCWebSocketDebugger` from. I can't seem to find it @tradziej?

**Comment by lifuzu** [comment]
Hi all, this pull request can fix the build issue with replacing the RTCWebSocketDebugger with RTCWebSocket: https://github.com/asamiller/den/pull/6
